/**
 * Auto-generated API documentation navigation.
 * This file is automatically generated by the docs plugin.
 * Do not edit manually.
 */

export interface NavItem {
  title: string;
  path: string;
  children?: NavItem[];
}

export const apiNav: NavItem[] = [
  {
    "title": "+page.server",
    "path": "/api/+page.server"
  },
  {
    "title": "Content",
    "path": "/api/content"
  }
] as const;
